import { motion } from "framer-motion";
import { ShieldCheck, AlertTriangle, XCircle, Copy, Check, Clock, Cpu, Activity, Globe } from "lucide-react";
import { useState } from "react";

interface ReportCardProps {
  type: "video" | "audio" | "url" | "text";
  score: number;
  riskLevel: string;
  details: Record<string, string | number>;
  timestamp?: string;
}

const typeLabels: Record<string, string> = {
  video: "Deepfake Video Analysis",
  audio: "Voice Scam Detection",
  url: "URL Threat Analysis",
  text: "Text Credibility Analysis",
};

const typeIcons: Record<string, typeof ShieldCheck> = {
  video: Activity,
  audio: Activity,
  url: Globe,
  text: Activity,
};

export default function ReportCard({ type, score, riskLevel, details, timestamp }: ReportCardProps) {
  const [copied, setCopied] = useState(false);

  const isGood = score >= 70;
  const isMedium = score >= 40 && score < 70;

  const borderColor = isGood
    ? "border-emerald-500/40"
    : isMedium
    ? "border-amber-500/40"
    : "border-red-500/40";

  const gradientFrom = isGood
    ? "from-emerald-500/10"
    : isMedium
    ? "from-amber-500/10"
    : "from-red-500/10";

  const StatusIcon = isGood ? ShieldCheck : isMedium ? AlertTriangle : XCircle;
  const statusColor = isGood ? "text-emerald-400" : isMedium ? "text-amber-400" : "text-red-400";

  const handleCopy = async () => {
    const text = [
      `TRUTHSHIELD ${typeLabels[type]} Report`,
      `Date: ${timestamp || new Date().toISOString()}`,
      `Score: ${score}%`,
      `Risk Level: ${riskLevel}`,
      "",
      "Details:",
      ...Object.entries(details).map(([k, v]) => `  ${k}: ${v}`),
      "",
      "— Generated by TRUTHSHIELD AI Digital Trust Engine",
    ].join("\n");

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard API not available
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      className={`rounded-xl border ${borderColor} bg-gradient-to-br ${gradientFrom} to-slate-900/80 backdrop-blur-xl p-6 relative overflow-hidden`}
    >
      {/* Gradient top bar */}
      <div className={`absolute top-0 left-0 right-0 h-1 bg-gradient-to-r ${
        isGood ? "from-emerald-500 to-cyan-500" : isMedium ? "from-amber-500 to-orange-500" : "from-red-500 to-rose-500"
      }`} />

      <div className="flex items-start justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className={`w-10 h-10 rounded-lg bg-slate-800/80 border border-slate-600/30 flex items-center justify-center`}>
            <StatusIcon className={`w-5 h-5 ${statusColor}`} />
          </div>
          <div>
            <h3 className="font-display font-semibold text-slate-100 text-sm">{typeLabels[type]}</h3>
            <p className="text-[11px] text-slate-500 flex items-center gap-1 mt-0.5">
              <Clock className="w-3 h-3" />
              {timestamp || new Date().toLocaleString()}
            </p>
          </div>
        </div>
        <button
          onClick={handleCopy}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-slate-600/30 bg-slate-800/50 text-xs text-slate-400 hover:text-slate-200 hover:border-cyan-500/40 transition-all"
        >
          {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
          {copied ? "Copied" : "Copy Report"}
        </button>
      </div>

      <div className="flex items-center gap-4 mb-4">
        <div className={`text-4xl font-display font-bold ${statusColor}`}>
          {Math.round(score)}%
        </div>
        <div className={`px-3 py-1 rounded-full text-xs font-semibold border ${
          isGood
            ? "bg-emerald-500/15 border-emerald-500/40 text-emerald-300"
            : isMedium
            ? "bg-amber-500/15 border-amber-500/40 text-amber-300"
            : "bg-red-500/15 border-red-500/40 text-red-300"
        }`}>
          {riskLevel}
        </div>
      </div>

      <div className="grid grid-cols-2 gap-3">
        {Object.entries(details).map(([key, value]) => (
          <div key={key} className="flex items-center gap-2 text-xs">
            <Cpu className="w-3.5 h-3.5 text-slate-500 flex-shrink-0" />
            <span className="text-slate-500">{key}:</span>
            <span className="text-slate-300 font-medium truncate">{String(value)}</span>
          </div>
        ))}
      </div>

      <div className="mt-4 pt-3 border-t border-slate-700/30 text-center">
        <p className="text-[10px] text-slate-600 uppercase tracking-widest font-medium">
          TRUTHSHIELD AI Digital Trust Engine
        </p>
      </div>
    </motion.div>
  );
}
